name: Java CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Build with Maven
      - name: Build with Maven
        run: mvn clean install

       
      # Step 4: Run tests
      - name: Run tests
        run: mvn test

      # Step 5: Set up Docker
      - name: set up Docker buildx
        uses: docker/setup-buildx-action@v3

      # Step 6: login to Docker Hub
      - name: login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Step 7: Build docker image
      - name: build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/bench-project:latest .

      # Step 8: Push Docker image
      - name: push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/bench-project:latest

      
      
